[package]
name = "tsar-client"
version = "1.0.4"
description = "Official wrapper for the TSAR Client API"
repository = "https://github.com/tsarcc/tsar-rust"
keywords = ["api", "framework", "windows", "macos", "linux"]
categories = ["api-bindings"]
authors = ["x <x@tsar.cc>"]
homepage = "https://tsar.cc/"
edition = "2021"
license = "MIT"
include = ["**/*.rs", "Cargo.toml"]

[dependencies]
reqwest = { version = "0.11.0", features = ['json', 'blocking'] }
serde_json = { version = "1" }
open = "5.0.0"
thiserror = "1.0.0"
base64 = "0.22.0"
p256 = { version = "0.13.2", features = ["ecdsa-core"] }
hardware-id = "0.3.0"
